# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 885a4467607786208362ff741ca0329edc0e729189535d57726813e088d7d4369b81200332a29c93a5168b4a4befdcb45c06e5c1a78dd8dc82fb66712e538d82

test:
  secret_key_base: dae383aeef91bfb8a435473071acbe82481fe8d2d1bc8c69a27acc69d2d541510d9e3fd36838d3b395fea6fe6be8c36df677e75df84d3d82f628f91ce704667c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
